### ISSUE TITLE
Docker build fail to create runable image

### ISSUE THREAD

**Issue by christian-kessler** [flant/curator-opensearch#28]
Hi,
I tried to create an image as is, but ldd prints a lot of issues:

docker build -t xyz .
[...]
Error relocating /usr/local/lib/python3.11/lib-dynload/termios.cpython-311-x86_64-linux-musl.so: _Py_NoneStruct: symbol not found
Error relocating /usr/local/lib/python3.11/lib-dynload/termios.cpython-311-x86_64-linux-musl.so: PyExc_OverflowError: symbol not found
Error relocating /usr/local/lib/python3.11/lib-dynload/termios.cpython-311-x86_64-linux-musl.so: PyExc_TypeError: symbol not found
[...]

Although the build is going to complete, but the image is not startable, because there is no executable

Do I miss something?
thank you for your help!

**Comment by uzhinskiy** [comment]
Hello. 
Thank you for your request. We have fixed the [Dockerfile](https://github.com/flant/curator-opensearch/blob/main/Dockerfile).
